try {
  // risky code
  let user;
console.log(username)
} catch (e) {
    console.log("Caught error:", e);
throw new Error("Cannot divide by zero");

} 